//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableOrder.Terminal.Table.Resources.Strings {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableOrder.Terminal.Table.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string AfterMealTag {
            get {
                return ResourceManager.GetString("AfterMealTag", resourceCulture);
            }
        }

        internal static string BadgeLimited {
            get {
                return ResourceManager.GetString("BadgeLimited", resourceCulture);
            }
        }

        internal static string BadgeNew {
            get {
                return ResourceManager.GetString("BadgeNew", resourceCulture);
            }
        }

        internal static string BadgePopular {
            get {
                return ResourceManager.GetString("BadgePopular", resourceCulture);
            }
        }

        internal static string BadgeRecommended {
            get {
                return ResourceManager.GetString("BadgeRecommended", resourceCulture);
            }
        }

        internal static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }

        internal static string CallAcknowledged {
            get {
                return ResourceManager.GetString("CallAcknowledged", resourceCulture);
            }
        }

        internal static string CallMessage {
            get {
                return ResourceManager.GetString("CallMessage", resourceCulture);
            }
        }

        internal static string CallOpen {
            get {
                return ResourceManager.GetString("CallOpen", resourceCulture);
            }
        }

        internal static string CallTitle {
            get {
                return ResourceManager.GetString("CallTitle", resourceCulture);
            }
        }

        internal static string CardInstruction {
            get {
                return ResourceManager.GetString("CardInstruction", resourceCulture);
            }
        }

        internal static string CheckoutBackToMenu {
            get {
                return ResourceManager.GetString("CheckoutBackToMenu", resourceCulture);
            }
        }

        internal static string CheckoutCompleted {
            get {
                return ResourceManager.GetString("CheckoutCompleted", resourceCulture);
            }
        }

        internal static string CheckoutDetails {
            get {
                return ResourceManager.GetString("CheckoutDetails", resourceCulture);
            }
        }

        internal static string CheckoutMethod {
            get {
                return ResourceManager.GetString("CheckoutMethod", resourceCulture);
            }
        }

        internal static string CheckoutNoOrder {
            get {
                return ResourceManager.GetString("CheckoutNoOrder", resourceCulture);
            }
        }

        internal static string CheckoutProceed {
            get {
                return ResourceManager.GetString("CheckoutProceed", resourceCulture);
            }
        }

        internal static string CheckoutSplitFormat {
            get {
                return ResourceManager.GetString("CheckoutSplitFormat", resourceCulture);
            }
        }

        internal static string CheckoutTaxFormat {
            get {
                return ResourceManager.GetString("CheckoutTaxFormat", resourceCulture);
            }
        }

        internal static string CheckoutTitle {
            get {
                return ResourceManager.GetString("CheckoutTitle", resourceCulture);
            }
        }

        internal static string CheckoutTotal {
            get {
                return ResourceManager.GetString("CheckoutTotal", resourceCulture);
            }
        }

        internal static string CheckoutUnordered {
            get {
                return ResourceManager.GetString("CheckoutUnordered", resourceCulture);
            }
        }

        internal static string CheckoutUnserved {
            get {
                return ResourceManager.GetString("CheckoutUnserved", resourceCulture);
            }
        }

        internal static string CommonBack {
            get {
                return ResourceManager.GetString("CommonBack", resourceCulture);
            }
        }

        internal static string CommonCancel {
            get {
                return ResourceManager.GetString("CommonCancel", resourceCulture);
            }
        }

        internal static string CommonClose {
            get {
                return ResourceManager.GetString("CommonClose", resourceCulture);
            }
        }

        internal static string CommonNo {
            get {
                return ResourceManager.GetString("CommonNo", resourceCulture);
            }
        }

        internal static string CommonOk {
            get {
                return ResourceManager.GetString("CommonOk", resourceCulture);
            }
        }

        internal static string CommonYes {
            get {
                return ResourceManager.GetString("CommonYes", resourceCulture);
            }
        }

        internal static string ConfirmDoneMessage {
            get {
                return ResourceManager.GetString("ConfirmDoneMessage", resourceCulture);
            }
        }

        internal static string ConfirmDoneTitle {
            get {
                return ResourceManager.GetString("ConfirmDoneTitle", resourceCulture);
            }
        }

        internal static string ConfirmRetry {
            get {
                return ResourceManager.GetString("ConfirmRetry", resourceCulture);
            }
        }

        internal static string ConfirmSubmit {
            get {
                return ResourceManager.GetString("ConfirmSubmit", resourceCulture);
            }
        }

        internal static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }

        internal static string CountFormat {
            get {
                return ResourceManager.GetString("CountFormat", resourceCulture);
            }
        }

        internal static string DetailAdd {
            get {
                return ResourceManager.GetString("DetailAdd", resourceCulture);
            }
        }

        internal static string DetailAllergenNone {
            get {
                return ResourceManager.GetString("DetailAllergenNone", resourceCulture);
            }
        }

        internal static string DetailAllergens {
            get {
                return ResourceManager.GetString("DetailAllergens", resourceCulture);
            }
        }

        internal static string DetailCalories {
            get {
                return ResourceManager.GetString("DetailCalories", resourceCulture);
            }
        }

        internal static string DetailCaloriesFormat {
            get {
                return ResourceManager.GetString("DetailCaloriesFormat", resourceCulture);
            }
        }

        internal static string DetailChooseOne {
            get {
                return ResourceManager.GetString("DetailChooseOne", resourceCulture);
            }
        }

        internal static string DetailChooseUpTo {
            get {
                return ResourceManager.GetString("DetailChooseUpTo", resourceCulture);
            }
        }

        internal static string DetailOptional {
            get {
                return ResourceManager.GetString("DetailOptional", resourceCulture);
            }
        }

        internal static string DetailQuantity {
            get {
                return ResourceManager.GetString("DetailQuantity", resourceCulture);
            }
        }

        internal static string DetailRequired {
            get {
                return ResourceManager.GetString("DetailRequired", resourceCulture);
            }
        }

        internal static string DetailTiming {
            get {
                return ResourceManager.GetString("DetailTiming", resourceCulture);
            }
        }

        internal static string DetailTimingAfterMeal {
            get {
                return ResourceManager.GetString("DetailTimingAfterMeal", resourceCulture);
            }
        }

        internal static string DetailTimingNow {
            get {
                return ResourceManager.GetString("DetailTimingNow", resourceCulture);
            }
        }

        internal static string DetailUpdate {
            get {
                return ResourceManager.GetString("DetailUpdate", resourceCulture);
            }
        }

        internal static string ErrorCheckoutInProgress {
            get {
                return ResourceManager.GetString("ErrorCheckoutInProgress", resourceCulture);
            }
        }

        internal static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }

        internal static string ErrorLastOrderPassed {
            get {
                return ResourceManager.GetString("ErrorLastOrderPassed", resourceCulture);
            }
        }

        internal static string ErrorLimit {
            get {
                return ResourceManager.GetString("ErrorLimit", resourceCulture);
            }
        }

        internal static string ErrorOrderingPaused {
            get {
                return ResourceManager.GetString("ErrorOrderingPaused", resourceCulture);
            }
        }

        internal static string ErrorSoldOut {
            get {
                return ResourceManager.GetString("ErrorSoldOut", resourceCulture);
            }
        }

        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }

        internal static string ErrorUnauthorized {
            get {
                return ResourceManager.GetString("ErrorUnauthorized", resourceCulture);
            }
        }

        internal static string ErrorUnavailable {
            get {
                return ResourceManager.GetString("ErrorUnavailable", resourceCulture);
            }
        }

        internal static string GuestAdults {
            get {
                return ResourceManager.GetString("GuestAdults", resourceCulture);
            }
        }

        internal static string GuestChildren {
            get {
                return ResourceManager.GetString("GuestChildren", resourceCulture);
            }
        }

        internal static string GuestChildrenHint {
            get {
                return ResourceManager.GetString("GuestChildrenHint", resourceCulture);
            }
        }

        internal static string GuestStart {
            get {
                return ResourceManager.GetString("GuestStart", resourceCulture);
            }
        }

        internal static string GuestTitle {
            get {
                return ResourceManager.GetString("GuestTitle", resourceCulture);
            }
        }

        internal static string GuestsFormat {
            get {
                return ResourceManager.GetString("GuestsFormat", resourceCulture);
            }
        }

        internal static string HeaderGuests {
            get {
                return ResourceManager.GetString("HeaderGuests", resourceCulture);
            }
        }

        internal static string HeaderTable {
            get {
                return ResourceManager.GetString("HeaderTable", resourceCulture);
            }
        }

        internal static string HistoryEmpty {
            get {
                return ResourceManager.GetString("HistoryEmpty", resourceCulture);
            }
        }

        internal static string HistoryHeldFormat {
            get {
                return ResourceManager.GetString("HistoryHeldFormat", resourceCulture);
            }
        }

        internal static string HistoryOrderFormat {
            get {
                return ResourceManager.GetString("HistoryOrderFormat", resourceCulture);
            }
        }

        internal static string HistoryRelease {
            get {
                return ResourceManager.GetString("HistoryRelease", resourceCulture);
            }
        }

        internal static string HistoryTitle {
            get {
                return ResourceManager.GetString("HistoryTitle", resourceCulture);
            }
        }

        internal static string HistoryTotal {
            get {
                return ResourceManager.GetString("HistoryTotal", resourceCulture);
            }
        }

        internal static string KioskDeviceOwner {
            get {
                return ResourceManager.GetString("KioskDeviceOwner", resourceCulture);
            }
        }

        internal static string KioskLocked {
            get {
                return ResourceManager.GetString("KioskLocked", resourceCulture);
            }
        }

        internal static string KioskManaged {
            get {
                return ResourceManager.GetString("KioskManaged", resourceCulture);
            }
        }

        internal static string KioskNone {
            get {
                return ResourceManager.GetString("KioskNone", resourceCulture);
            }
        }

        internal static string KioskReleased {
            get {
                return ResourceManager.GetString("KioskReleased", resourceCulture);
            }
        }

        internal static string KioskUnlocked {
            get {
                return ResourceManager.GetString("KioskUnlocked", resourceCulture);
            }
        }

        internal static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }

        internal static string LimitMessageFormat {
            get {
                return ResourceManager.GetString("LimitMessageFormat", resourceCulture);
            }
        }

        internal static string LimitTitle {
            get {
                return ResourceManager.GetString("LimitTitle", resourceCulture);
            }
        }

        internal static string ListSeparator {
            get {
                return ResourceManager.GetString("ListSeparator", resourceCulture);
            }
        }

        internal static string MenuCall {
            get {
                return ResourceManager.GetString("MenuCall", resourceCulture);
            }
        }

        internal static string MenuCartEmpty {
            get {
                return ResourceManager.GetString("MenuCartEmpty", resourceCulture);
            }
        }

        internal static string MenuCartEmptyHint {
            get {
                return ResourceManager.GetString("MenuCartEmptyHint", resourceCulture);
            }
        }

        internal static string MenuCartTitle {
            get {
                return ResourceManager.GetString("MenuCartTitle", resourceCulture);
            }
        }

        internal static string MenuCheckout {
            get {
                return ResourceManager.GetString("MenuCheckout", resourceCulture);
            }
        }

        internal static string MenuHistory {
            get {
                return ResourceManager.GetString("MenuHistory", resourceCulture);
            }
        }

        internal static string MenuLastOrderPassed {
            get {
                return ResourceManager.GetString("MenuLastOrderPassed", resourceCulture);
            }
        }

        internal static string MenuLastOrderSoonFormat {
            get {
                return ResourceManager.GetString("MenuLastOrderSoonFormat", resourceCulture);
            }
        }

        internal static string MenuOrderingPaused {
            get {
                return ResourceManager.GetString("MenuOrderingPaused", resourceCulture);
            }
        }

        internal static string MenuSubmit {
            get {
                return ResourceManager.GetString("MenuSubmit", resourceCulture);
            }
        }

        internal static string MethodCreditCard {
            get {
                return ResourceManager.GetString("MethodCreditCard", resourceCulture);
            }
        }

        internal static string MethodCreditCardHint {
            get {
                return ResourceManager.GetString("MethodCreditCardHint", resourceCulture);
            }
        }

        internal static string MethodQrCode {
            get {
                return ResourceManager.GetString("MethodQrCode", resourceCulture);
            }
        }

        internal static string MethodQrCodeHint {
            get {
                return ResourceManager.GetString("MethodQrCodeHint", resourceCulture);
            }
        }

        internal static string MethodRegister {
            get {
                return ResourceManager.GetString("MethodRegister", resourceCulture);
            }
        }

        internal static string MethodRegisterHint {
            get {
                return ResourceManager.GetString("MethodRegisterHint", resourceCulture);
            }
        }

        internal static string PaymentChange {
            get {
                return ResourceManager.GetString("PaymentChange", resourceCulture);
            }
        }

        internal static string PaymentFailed {
            get {
                return ResourceManager.GetString("PaymentFailed", resourceCulture);
            }
        }

        internal static string PaymentWaiting {
            get {
                return ResourceManager.GetString("PaymentWaiting", resourceCulture);
            }
        }

        internal static string QrInstruction {
            get {
                return ResourceManager.GetString("QrInstruction", resourceCulture);
            }
        }

        internal static string ReceiptCaption {
            get {
                return ResourceManager.GetString("ReceiptCaption", resourceCulture);
            }
        }

        internal static string ReceiptHint {
            get {
                return ResourceManager.GetString("ReceiptHint", resourceCulture);
            }
        }

        internal static string RegisterMessageFormat {
            get {
                return ResourceManager.GetString("RegisterMessageFormat", resourceCulture);
            }
        }

        internal static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }

        internal static string RuleConfirmMessage {
            get {
                return ResourceManager.GetString("RuleConfirmMessage", resourceCulture);
            }
        }

        internal static string RuleConfirmTitle {
            get {
                return ResourceManager.GetString("RuleConfirmTitle", resourceCulture);
            }
        }

        internal static string SetupChange {
            get {
                return ResourceManager.GetString("SetupChange", resourceCulture);
            }
        }

        internal static string SetupEndpoint {
            get {
                return ResourceManager.GetString("SetupEndpoint", resourceCulture);
            }
        }

        internal static string SetupEndpointHint {
            get {
                return ResourceManager.GetString("SetupEndpointHint", resourceCulture);
            }
        }

        internal static string SetupNotSet {
            get {
                return ResourceManager.GetString("SetupNotSet", resourceCulture);
            }
        }

        internal static string SetupSave {
            get {
                return ResourceManager.GetString("SetupSave", resourceCulture);
            }
        }

        internal static string SetupTableNo {
            get {
                return ResourceManager.GetString("SetupTableNo", resourceCulture);
            }
        }

        internal static string SetupTableNoHint {
            get {
                return ResourceManager.GetString("SetupTableNoHint", resourceCulture);
            }
        }

        internal static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }

        internal static string SoldOut {
            get {
                return ResourceManager.GetString("SoldOut", resourceCulture);
            }
        }

        internal static string StaffApp {
            get {
                return ResourceManager.GetString("StaffApp", resourceCulture);
            }
        }

        internal static string StaffBattery {
            get {
                return ResourceManager.GetString("StaffBattery", resourceCulture);
            }
        }

        internal static string StaffBatteryChargingFormat {
            get {
                return ResourceManager.GetString("StaffBatteryChargingFormat", resourceCulture);
            }
        }

        internal static string StaffBatteryFormat {
            get {
                return ResourceManager.GetString("StaffBatteryFormat", resourceCulture);
            }
        }

        internal static string StaffChangePin {
            get {
                return ResourceManager.GetString("StaffChangePin", resourceCulture);
            }
        }

        internal static string StaffConnected {
            get {
                return ResourceManager.GetString("StaffConnected", resourceCulture);
            }
        }

        internal static string StaffDevice {
            get {
                return ResourceManager.GetString("StaffDevice", resourceCulture);
            }
        }

        internal static string StaffDeviceId {
            get {
                return ResourceManager.GetString("StaffDeviceId", resourceCulture);
            }
        }

        internal static string StaffDisconnected {
            get {
                return ResourceManager.GetString("StaffDisconnected", resourceCulture);
            }
        }

        internal static string StaffEndpoint {
            get {
                return ResourceManager.GetString("StaffEndpoint", resourceCulture);
            }
        }

        internal static string StaffEndpointMock {
            get {
                return ResourceManager.GetString("StaffEndpointMock", resourceCulture);
            }
        }

        internal static string StaffInfo {
            get {
                return ResourceManager.GetString("StaffInfo", resourceCulture);
            }
        }

        internal static string StaffKiosk {
            get {
                return ResourceManager.GetString("StaffKiosk", resourceCulture);
            }
        }

        internal static string StaffKioskFormat {
            get {
                return ResourceManager.GetString("StaffKioskFormat", resourceCulture);
            }
        }

        internal static string StaffKioskHint {
            get {
                return ResourceManager.GetString("StaffKioskHint", resourceCulture);
            }
        }

        internal static string StaffKioskRelease {
            get {
                return ResourceManager.GetString("StaffKioskRelease", resourceCulture);
            }
        }

        internal static string StaffKioskRestore {
            get {
                return ResourceManager.GetString("StaffKioskRestore", resourceCulture);
            }
        }

        internal static string StaffKioskSettings {
            get {
                return ResourceManager.GetString("StaffKioskSettings", resourceCulture);
            }
        }

        internal static string StaffMock {
            get {
                return ResourceManager.GetString("StaffMock", resourceCulture);
            }
        }

        internal static string StaffMockAdvance {
            get {
                return ResourceManager.GetString("StaffMockAdvance", resourceCulture);
            }
        }

        internal static string StaffMockAdvanceDone {
            get {
                return ResourceManager.GetString("StaffMockAdvanceDone", resourceCulture);
            }
        }

        internal static string StaffMockCartEmpty {
            get {
                return ResourceManager.GetString("StaffMockCartEmpty", resourceCulture);
            }
        }

        internal static string StaffMockFailPayments {
            get {
                return ResourceManager.GetString("StaffMockFailPayments", resourceCulture);
            }
        }

        internal static string StaffMockHallOpen {
            get {
                return ResourceManager.GetString("StaffMockHallOpen", resourceCulture);
            }
        }

        internal static string StaffMockHallOpenFormat {
            get {
                return ResourceManager.GetString("StaffMockHallOpenFormat", resourceCulture);
            }
        }

        internal static string StaffMockHintFormat {
            get {
                return ResourceManager.GetString("StaffMockHintFormat", resourceCulture);
            }
        }

        internal static string StaffMockLastOrderNone {
            get {
                return ResourceManager.GetString("StaffMockLastOrderNone", resourceCulture);
            }
        }

        internal static string StaffMockLastOrderPassed {
            get {
                return ResourceManager.GetString("StaffMockLastOrderPassed", resourceCulture);
            }
        }

        internal static string StaffMockLastOrderSoon {
            get {
                return ResourceManager.GetString("StaffMockLastOrderSoon", resourceCulture);
            }
        }

        internal static string StaffMockNoVisit {
            get {
                return ResourceManager.GetString("StaffMockNoVisit", resourceCulture);
            }
        }

        internal static string StaffMockOffline {
            get {
                return ResourceManager.GetString("StaffMockOffline", resourceCulture);
            }
        }

        internal static string StaffMockOnline {
            get {
                return ResourceManager.GetString("StaffMockOnline", resourceCulture);
            }
        }

        internal static string StaffMockPassPayments {
            get {
                return ResourceManager.GetString("StaffMockPassPayments", resourceCulture);
            }
        }

        internal static string StaffMockPause {
            get {
                return ResourceManager.GetString("StaffMockPause", resourceCulture);
            }
        }

        internal static string StaffMockRegisterPay {
            get {
                return ResourceManager.GetString("StaffMockRegisterPay", resourceCulture);
            }
        }

        internal static string StaffMockRegisterPayFormat {
            get {
                return ResourceManager.GetString("StaffMockRegisterPayFormat", resourceCulture);
            }
        }

        internal static string StaffMockRestock {
            get {
                return ResourceManager.GetString("StaffMockRestock", resourceCulture);
            }
        }

        internal static string StaffMockRestockDone {
            get {
                return ResourceManager.GetString("StaffMockRestockDone", resourceCulture);
            }
        }

        internal static string StaffMockResume {
            get {
                return ResourceManager.GetString("StaffMockResume", resourceCulture);
            }
        }

        internal static string StaffMockSellOut {
            get {
                return ResourceManager.GetString("StaffMockSellOut", resourceCulture);
            }
        }

        internal static string StaffMockSoldOutDone {
            get {
                return ResourceManager.GetString("StaffMockSoldOutDone", resourceCulture);
            }
        }

        internal static string StaffNetwork {
            get {
                return ResourceManager.GetString("StaffNetwork", resourceCulture);
            }
        }

        internal static string StaffNewPin {
            get {
                return ResourceManager.GetString("StaffNewPin", resourceCulture);
            }
        }

        internal static string StaffNewPinAgain {
            get {
                return ResourceManager.GetString("StaffNewPinAgain", resourceCulture);
            }
        }

        internal static string StaffOpenVisit {
            get {
                return ResourceManager.GetString("StaffOpenVisit", resourceCulture);
            }
        }

        internal static string StaffPin {
            get {
                return ResourceManager.GetString("StaffPin", resourceCulture);
            }
        }

        internal static string StaffPinChanged {
            get {
                return ResourceManager.GetString("StaffPinChanged", resourceCulture);
            }
        }

        internal static string StaffPinLength {
            get {
                return ResourceManager.GetString("StaffPinLength", resourceCulture);
            }
        }

        internal static string StaffPinMismatch {
            get {
                return ResourceManager.GetString("StaffPinMismatch", resourceCulture);
            }
        }

        internal static string StaffPinWrong {
            get {
                return ResourceManager.GetString("StaffPinWrong", resourceCulture);
            }
        }

        internal static string StaffTitle {
            get {
                return ResourceManager.GetString("StaffTitle", resourceCulture);
            }
        }

        internal static string StaffVisit {
            get {
                return ResourceManager.GetString("StaffVisit", resourceCulture);
            }
        }

        internal static string StaffVisitOpen {
            get {
                return ResourceManager.GetString("StaffVisitOpen", resourceCulture);
            }
        }

        internal static string StandbyMessage {
            get {
                return ResourceManager.GetString("StandbyMessage", resourceCulture);
            }
        }

        internal static string StandbyStart {
            get {
                return ResourceManager.GetString("StandbyStart", resourceCulture);
            }
        }

        internal static string StandbyWaiting {
            get {
                return ResourceManager.GetString("StandbyWaiting", resourceCulture);
            }
        }

        internal static string StandbyWelcome {
            get {
                return ResourceManager.GetString("StandbyWelcome", resourceCulture);
            }
        }

        internal static string StartupRetry {
            get {
                return ResourceManager.GetString("StartupRetry", resourceCulture);
            }
        }

        internal static string StartupSetup {
            get {
                return ResourceManager.GetString("StartupSetup", resourceCulture);
            }
        }

        internal static string StartupStepConnect {
            get {
                return ResourceManager.GetString("StartupStepConnect", resourceCulture);
            }
        }

        internal static string StartupStepMenu {
            get {
                return ResourceManager.GetString("StartupStepMenu", resourceCulture);
            }
        }

        internal static string StartupStepReady {
            get {
                return ResourceManager.GetString("StartupStepReady", resourceCulture);
            }
        }

        internal static string StartupStepSettings {
            get {
                return ResourceManager.GetString("StartupStepSettings", resourceCulture);
            }
        }

        internal static string StartupStepVisit {
            get {
                return ResourceManager.GetString("StartupStepVisit", resourceCulture);
            }
        }

        internal static string StatusCancelled {
            get {
                return ResourceManager.GetString("StatusCancelled", resourceCulture);
            }
        }

        internal static string StatusCooking {
            get {
                return ResourceManager.GetString("StatusCooking", resourceCulture);
            }
        }

        internal static string StatusHeld {
            get {
                return ResourceManager.GetString("StatusHeld", resourceCulture);
            }
        }

        internal static string StatusOrdered {
            get {
                return ResourceManager.GetString("StatusOrdered", resourceCulture);
            }
        }

        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }

        internal static string StatusServed {
            get {
                return ResourceManager.GetString("StatusServed", resourceCulture);
            }
        }

        internal static string StockRemainingFormat {
            get {
                return ResourceManager.GetString("StockRemainingFormat", resourceCulture);
            }
        }

        internal static string SuggestionAdd {
            get {
                return ResourceManager.GetString("SuggestionAdd", resourceCulture);
            }
        }

        internal static string SuggestionDefault {
            get {
                return ResourceManager.GetString("SuggestionDefault", resourceCulture);
            }
        }

        internal static string SuggestionRemainingFormat {
            get {
                return ResourceManager.GetString("SuggestionRemainingFormat", resourceCulture);
            }
        }

        internal static string TableFormat {
            get {
                return ResourceManager.GetString("TableFormat", resourceCulture);
            }
        }

        internal static string ThanksMessage {
            get {
                return ResourceManager.GetString("ThanksMessage", resourceCulture);
            }
        }

        internal static string ThanksTitle {
            get {
                return ResourceManager.GetString("ThanksTitle", resourceCulture);
            }
        }

        internal static string TotalCaption {
            get {
                return ResourceManager.GetString("TotalCaption", resourceCulture);
            }
        }
    }
}
