//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableOrder.KitchenApp.Resources.Strings {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableOrder.KitchenApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        internal static string ListSeparator {
            get {
                return ResourceManager.GetString("ListSeparator", resourceCulture);
            }
        }

        internal static string CommonBack {
            get {
                return ResourceManager.GetString("CommonBack", resourceCulture);
            }
        }

        internal static string CommonClose {
            get {
                return ResourceManager.GetString("CommonClose", resourceCulture);
            }
        }

        internal static string NotFoundTitle {
            get {
                return ResourceManager.GetString("NotFoundTitle", resourceCulture);
            }
        }

        internal static string NotFoundBack {
            get {
                return ResourceManager.GetString("NotFoundBack", resourceCulture);
            }
        }

        internal static string NumpadClear {
            get {
                return ResourceManager.GetString("NumpadClear", resourceCulture);
            }
        }

        internal static string StartupStepSettings {
            get {
                return ResourceManager.GetString("StartupStepSettings", resourceCulture);
            }
        }

        internal static string StartupStepConnect {
            get {
                return ResourceManager.GetString("StartupStepConnect", resourceCulture);
            }
        }

        internal static string StartupStepStore {
            get {
                return ResourceManager.GetString("StartupStepStore", resourceCulture);
            }
        }

        internal static string StartupStepTickets {
            get {
                return ResourceManager.GetString("StartupStepTickets", resourceCulture);
            }
        }

        internal static string StartupStepReady {
            get {
                return ResourceManager.GetString("StartupStepReady", resourceCulture);
            }
        }

        internal static string StartupNotKitchen {
            get {
                return ResourceManager.GetString("StartupNotKitchen", resourceCulture);
            }
        }

        internal static string StartupRetry {
            get {
                return ResourceManager.GetString("StartupRetry", resourceCulture);
            }
        }

        internal static string StartupSetup {
            get {
                return ResourceManager.GetString("StartupSetup", resourceCulture);
            }
        }

        internal static string StartupAutoRetryFormat {
            get {
                return ResourceManager.GetString("StartupAutoRetryFormat", resourceCulture);
            }
        }

        internal static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }

        internal static string SetupEndpoint {
            get {
                return ResourceManager.GetString("SetupEndpoint", resourceCulture);
            }
        }

        internal static string SetupRegistration {
            get {
                return ResourceManager.GetString("SetupRegistration", resourceCulture);
            }
        }

        internal static string SetupRegisteredFormat {
            get {
                return ResourceManager.GetString("SetupRegisteredFormat", resourceCulture);
            }
        }

        internal static string SetupNotRegistered {
            get {
                return ResourceManager.GetString("SetupNotRegistered", resourceCulture);
            }
        }

        internal static string SetupPairingCode {
            get {
                return ResourceManager.GetString("SetupPairingCode", resourceCulture);
            }
        }

        internal static string SetupPairingCodeHint {
            get {
                return ResourceManager.GetString("SetupPairingCodeHint", resourceCulture);
            }
        }

        internal static string SetupNotEntered {
            get {
                return ResourceManager.GetString("SetupNotEntered", resourceCulture);
            }
        }

        internal static string SetupRegister {
            get {
                return ResourceManager.GetString("SetupRegister", resourceCulture);
            }
        }

        internal static string DeviceTitle {
            get {
                return ResourceManager.GetString("DeviceTitle", resourceCulture);
            }
        }

        internal static string DeviceStore {
            get {
                return ResourceManager.GetString("DeviceStore", resourceCulture);
            }
        }

        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }

        internal static string DeviceStations {
            get {
                return ResourceManager.GetString("DeviceStations", resourceCulture);
            }
        }

        internal static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }

        internal static string DeviceEndpoint {
            get {
                return ResourceManager.GetString("DeviceEndpoint", resourceCulture);
            }
        }

        internal static string DeviceSound {
            get {
                return ResourceManager.GetString("DeviceSound", resourceCulture);
            }
        }

        internal static string DeviceSoundReady {
            get {
                return ResourceManager.GetString("DeviceSoundReady", resourceCulture);
            }
        }

        internal static string DeviceSoundWaiting {
            get {
                return ResourceManager.GetString("DeviceSoundWaiting", resourceCulture);
            }
        }

        internal static string DeviceVersion {
            get {
                return ResourceManager.GetString("DeviceVersion", resourceCulture);
            }
        }

        internal static string DeviceSetup {
            get {
                return ResourceManager.GetString("DeviceSetup", resourceCulture);
            }
        }

        internal static string StationAll {
            get {
                return ResourceManager.GetString("StationAll", resourceCulture);
            }
        }

        internal static string TicketsSoundHint {
            get {
                return ResourceManager.GetString("TicketsSoundHint", resourceCulture);
            }
        }

        internal static string TicketsEmpty {
            get {
                return ResourceManager.GetString("TicketsEmpty", resourceCulture);
            }
        }

        internal static string TicketTableFormat {
            get {
                return ResourceManager.GetString("TicketTableFormat", resourceCulture);
            }
        }

        internal static string TicketOrderFormat {
            get {
                return ResourceManager.GetString("TicketOrderFormat", resourceCulture);
            }
        }

        internal static string TicketElapsedFormat {
            get {
                return ResourceManager.GetString("TicketElapsedFormat", resourceCulture);
            }
        }

        internal static string TicketBump {
            get {
                return ResourceManager.GetString("TicketBump", resourceCulture);
            }
        }

        internal static string TicketRecall {
            get {
                return ResourceManager.GetString("TicketRecall", resourceCulture);
            }
        }

        internal static string LineCooking {
            get {
                return ResourceManager.GetString("LineCooking", resourceCulture);
            }
        }

        internal static string LineReady {
            get {
                return ResourceManager.GetString("LineReady", resourceCulture);
            }
        }

        internal static string LineServed {
            get {
                return ResourceManager.GetString("LineServed", resourceCulture);
            }
        }

        internal static string LineCancelled {
            get {
                return ResourceManager.GetString("LineCancelled", resourceCulture);
            }
        }

        internal static string FooterDone {
            get {
                return ResourceManager.GetString("FooterDone", resourceCulture);
            }
        }

        internal static string FooterStock {
            get {
                return ResourceManager.GetString("FooterStock", resourceCulture);
            }
        }

        internal static string FooterDevice {
            get {
                return ResourceManager.GetString("FooterDevice", resourceCulture);
            }
        }

        internal static string DoneTitle {
            get {
                return ResourceManager.GetString("DoneTitle", resourceCulture);
            }
        }

        internal static string DoneHint {
            get {
                return ResourceManager.GetString("DoneHint", resourceCulture);
            }
        }

        internal static string DoneEmpty {
            get {
                return ResourceManager.GetString("DoneEmpty", resourceCulture);
            }
        }

        internal static string StockTitle {
            get {
                return ResourceManager.GetString("StockTitle", resourceCulture);
            }
        }

        internal static string StockTabLimited {
            get {
                return ResourceManager.GetString("StockTabLimited", resourceCulture);
            }
        }

        internal static string StockTabOptions {
            get {
                return ResourceManager.GetString("StockTabOptions", resourceCulture);
            }
        }

        internal static string StockAvailable {
            get {
                return ResourceManager.GetString("StockAvailable", resourceCulture);
            }
        }

        internal static string StockSetRemaining {
            get {
                return ResourceManager.GetString("StockSetRemaining", resourceCulture);
            }
        }

        internal static string StockSoldOut {
            get {
                return ResourceManager.GetString("StockSoldOut", resourceCulture);
            }
        }

        internal static string StockRemainingFormat {
            get {
                return ResourceManager.GetString("StockRemainingFormat", resourceCulture);
            }
        }

        internal static string StockCurrentFormat {
            get {
                return ResourceManager.GetString("StockCurrentFormat", resourceCulture);
            }
        }

        internal static string StockRemainingTitle {
            get {
                return ResourceManager.GetString("StockRemainingTitle", resourceCulture);
            }
        }

        internal static string StockDecide {
            get {
                return ResourceManager.GetString("StockDecide", resourceCulture);
            }
        }

        internal static string StockEmptyLimited {
            get {
                return ResourceManager.GetString("StockEmptyLimited", resourceCulture);
            }
        }

        internal static string StockEmpty {
            get {
                return ResourceManager.GetString("StockEmpty", resourceCulture);
            }
        }

        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }

        internal static string CommonOk {
            get {
                return ResourceManager.GetString("CommonOk", resourceCulture);
            }
        }

        internal static string ErrorUnavailable {
            get {
                return ResourceManager.GetString("ErrorUnavailable", resourceCulture);
            }
        }

        internal static string ErrorUnauthorized {
            get {
                return ResourceManager.GetString("ErrorUnauthorized", resourceCulture);
            }
        }

        internal static string ErrorTenantSuspended {
            get {
                return ResourceManager.GetString("ErrorTenantSuspended", resourceCulture);
            }
        }

        internal static string ErrorPairingCodeInvalid {
            get {
                return ResourceManager.GetString("ErrorPairingCodeInvalid", resourceCulture);
            }
        }

        internal static string ErrorDeviceKind {
            get {
                return ResourceManager.GetString("ErrorDeviceKind", resourceCulture);
            }
        }

        internal static string ErrorDeviceKey {
            get {
                return ResourceManager.GetString("ErrorDeviceKey", resourceCulture);
            }
        }

        internal static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }
    }
}
