//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableOrder.Terminal.Resources.Strings {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TerminalResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TerminalResources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableOrder.Terminal.Resources.Strings.TerminalResources", typeof(TerminalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string CommonCancel {
            get {
                return ResourceManager.GetString("CommonCancel", resourceCulture);
            }
        }

        public static string CommonOk {
            get {
                return ResourceManager.GetString("CommonOk", resourceCulture);
            }
        }

        public static string SetupPairingCode {
            get {
                return ResourceManager.GetString("SetupPairingCode", resourceCulture);
            }
        }

        public static string StaffPin {
            get {
                return ResourceManager.GetString("StaffPin", resourceCulture);
            }
        }

        public static string StaffPinLocked {
            get {
                return ResourceManager.GetString("StaffPinLocked", resourceCulture);
            }
        }

        public static string StaffPinWrong {
            get {
                return ResourceManager.GetString("StaffPinWrong", resourceCulture);
            }
        }

        public static string StaffTitle {
            get {
                return ResourceManager.GetString("StaffTitle", resourceCulture);
            }
        }
    }
}
