//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TableOrder.HallApp.Resources.Strings {
    using System;


    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TableOrder.HallApp.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        internal static string ListSeparator {
            get {
                return ResourceManager.GetString("ListSeparator", resourceCulture);
            }
        }

        internal static string TabSeats {
            get {
                return ResourceManager.GetString("TabSeats", resourceCulture);
            }
        }

        internal static string TabCalls {
            get {
                return ResourceManager.GetString("TabCalls", resourceCulture);
            }
        }

        internal static string TabServing {
            get {
                return ResourceManager.GetString("TabServing", resourceCulture);
            }
        }

        internal static string TabStock {
            get {
                return ResourceManager.GetString("TabStock", resourceCulture);
            }
        }

        internal static string NoticeOrderingPaused {
            get {
                return ResourceManager.GetString("NoticeOrderingPaused", resourceCulture);
            }
        }

        internal static string StartupStepSettings {
            get {
                return ResourceManager.GetString("StartupStepSettings", resourceCulture);
            }
        }

        internal static string StartupStepRegister {
            get {
                return ResourceManager.GetString("StartupStepRegister", resourceCulture);
            }
        }

        internal static string StartupStepConnect {
            get {
                return ResourceManager.GetString("StartupStepConnect", resourceCulture);
            }
        }

        internal static string StartupStepMenu {
            get {
                return ResourceManager.GetString("StartupStepMenu", resourceCulture);
            }
        }

        internal static string StartupStepFloor {
            get {
                return ResourceManager.GetString("StartupStepFloor", resourceCulture);
            }
        }

        internal static string StartupStepReady {
            get {
                return ResourceManager.GetString("StartupStepReady", resourceCulture);
            }
        }

        internal static string StartupNotHall {
            get {
                return ResourceManager.GetString("StartupNotHall", resourceCulture);
            }
        }

        internal static string StartupRetry {
            get {
                return ResourceManager.GetString("StartupRetry", resourceCulture);
            }
        }

        internal static string StartupSetup {
            get {
                return ResourceManager.GetString("StartupSetup", resourceCulture);
            }
        }

        internal static string StartupAutoRetryFormat {
            get {
                return ResourceManager.GetString("StartupAutoRetryFormat", resourceCulture);
            }
        }

        internal static string StartupAutoRetryMinutesFormat {
            get {
                return ResourceManager.GetString("StartupAutoRetryMinutesFormat", resourceCulture);
            }
        }

        internal static string SetupTitle {
            get {
                return ResourceManager.GetString("SetupTitle", resourceCulture);
            }
        }

        internal static string SetupEndpoint {
            get {
                return ResourceManager.GetString("SetupEndpoint", resourceCulture);
            }
        }

        internal static string SetupEndpointHint {
            get {
                return ResourceManager.GetString("SetupEndpointHint", resourceCulture);
            }
        }

        internal static string SetupEndpointManaged {
            get {
                return ResourceManager.GetString("SetupEndpointManaged", resourceCulture);
            }
        }

        internal static string SetupRegistration {
            get {
                return ResourceManager.GetString("SetupRegistration", resourceCulture);
            }
        }

        internal static string SetupRegisteredFormat {
            get {
                return ResourceManager.GetString("SetupRegisteredFormat", resourceCulture);
            }
        }

        internal static string SetupNotRegistered {
            get {
                return ResourceManager.GetString("SetupNotRegistered", resourceCulture);
            }
        }

        internal static string SetupRegistrationHint {
            get {
                return ResourceManager.GetString("SetupRegistrationHint", resourceCulture);
            }
        }

        internal static string SetupEnrollmentHint {
            get {
                return ResourceManager.GetString("SetupEnrollmentHint", resourceCulture);
            }
        }

        internal static string SetupRegisterHint {
            get {
                return ResourceManager.GetString("SetupRegisterHint", resourceCulture);
            }
        }

        internal static string SetupPairingCodeHint {
            get {
                return ResourceManager.GetString("SetupPairingCodeHint", resourceCulture);
            }
        }

        internal static string SetupEnter {
            get {
                return ResourceManager.GetString("SetupEnter", resourceCulture);
            }
        }

        internal static string SetupNotEntered {
            get {
                return ResourceManager.GetString("SetupNotEntered", resourceCulture);
            }
        }

        internal static string SetupSave {
            get {
                return ResourceManager.GetString("SetupSave", resourceCulture);
            }
        }

        internal static string SetupRegister {
            get {
                return ResourceManager.GetString("SetupRegister", resourceCulture);
            }
        }

        internal static string DeviceTitle {
            get {
                return ResourceManager.GetString("DeviceTitle", resourceCulture);
            }
        }

        internal static string DeviceInfo {
            get {
                return ResourceManager.GetString("DeviceInfo", resourceCulture);
            }
        }

        internal static string DeviceStore {
            get {
                return ResourceManager.GetString("DeviceStore", resourceCulture);
            }
        }

        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }

        internal static string DeviceId {
            get {
                return ResourceManager.GetString("DeviceId", resourceCulture);
            }
        }

        internal static string DeviceEndpoint {
            get {
                return ResourceManager.GetString("DeviceEndpoint", resourceCulture);
            }
        }

        internal static string DeviceKiosk {
            get {
                return ResourceManager.GetString("DeviceKiosk", resourceCulture);
            }
        }

        internal static string DeviceManaged {
            get {
                return ResourceManager.GetString("DeviceManaged", resourceCulture);
            }
        }

        internal static string DeviceManagedNone {
            get {
                return ResourceManager.GetString("DeviceManagedNone", resourceCulture);
            }
        }

        internal static string DeviceEnrollmentToken {
            get {
                return ResourceManager.GetString("DeviceEnrollmentToken", resourceCulture);
            }
        }

        internal static string DeviceBattery {
            get {
                return ResourceManager.GetString("DeviceBattery", resourceCulture);
            }
        }

        internal static string DeviceBatteryFormat {
            get {
                return ResourceManager.GetString("DeviceBatteryFormat", resourceCulture);
            }
        }

        internal static string DeviceBatteryChargingFormat {
            get {
                return ResourceManager.GetString("DeviceBatteryChargingFormat", resourceCulture);
            }
        }

        internal static string DeviceNetwork {
            get {
                return ResourceManager.GetString("DeviceNetwork", resourceCulture);
            }
        }

        internal static string DeviceConnected {
            get {
                return ResourceManager.GetString("DeviceConnected", resourceCulture);
            }
        }

        internal static string DeviceDisconnected {
            get {
                return ResourceManager.GetString("DeviceDisconnected", resourceCulture);
            }
        }

        internal static string DeviceApp {
            get {
                return ResourceManager.GetString("DeviceApp", resourceCulture);
            }
        }

        internal static string DeviceSettings {
            get {
                return ResourceManager.GetString("DeviceSettings", resourceCulture);
            }
        }

        internal static string DeviceKioskFormat {
            get {
                return ResourceManager.GetString("DeviceKioskFormat", resourceCulture);
            }
        }

        internal static string DeviceKioskRelease {
            get {
                return ResourceManager.GetString("DeviceKioskRelease", resourceCulture);
            }
        }

        internal static string DeviceKioskRestore {
            get {
                return ResourceManager.GetString("DeviceKioskRestore", resourceCulture);
            }
        }

        internal static string DeviceKioskSettings {
            get {
                return ResourceManager.GetString("DeviceKioskSettings", resourceCulture);
            }
        }

        internal static string DeviceKioskHint {
            get {
                return ResourceManager.GetString("DeviceKioskHint", resourceCulture);
            }
        }

        internal static string KioskManaged {
            get {
                return ResourceManager.GetString("KioskManaged", resourceCulture);
            }
        }

        internal static string KioskDeviceOwner {
            get {
                return ResourceManager.GetString("KioskDeviceOwner", resourceCulture);
            }
        }

        internal static string KioskNone {
            get {
                return ResourceManager.GetString("KioskNone", resourceCulture);
            }
        }

        internal static string KioskReleased {
            get {
                return ResourceManager.GetString("KioskReleased", resourceCulture);
            }
        }

        internal static string KioskLocked {
            get {
                return ResourceManager.GetString("KioskLocked", resourceCulture);
            }
        }

        internal static string KioskUnlocked {
            get {
                return ResourceManager.GetString("KioskUnlocked", resourceCulture);
            }
        }

        internal static string CommonBack {
            get {
                return ResourceManager.GetString("CommonBack", resourceCulture);
            }
        }

        internal static string TableFormat {
            get {
                return ResourceManager.GetString("TableFormat", resourceCulture);
            }
        }

        internal static string SeatVacant {
            get {
                return ResourceManager.GetString("SeatVacant", resourceCulture);
            }
        }

        internal static string SeatOpen {
            get {
                return ResourceManager.GetString("SeatOpen", resourceCulture);
            }
        }

        internal static string SeatPaying {
            get {
                return ResourceManager.GetString("SeatPaying", resourceCulture);
            }
        }

        internal static string CapacityFormat {
            get {
                return ResourceManager.GetString("CapacityFormat", resourceCulture);
            }
        }

        internal static string GuestsFormat {
            get {
                return ResourceManager.GetString("GuestsFormat", resourceCulture);
            }
        }

        internal static string ElapsedMinutesFormat {
            get {
                return ResourceManager.GetString("ElapsedMinutesFormat", resourceCulture);
            }
        }

        internal static string ElapsedHoursFormat {
            get {
                return ResourceManager.GetString("ElapsedHoursFormat", resourceCulture);
            }
        }

        internal static string UnservedFormat {
            get {
                return ResourceManager.GetString("UnservedFormat", resourceCulture);
            }
        }

        internal static string CallsFormat {
            get {
                return ResourceManager.GetString("CallsFormat", resourceCulture);
            }
        }

        internal static string GuideTitleFormat {
            get {
                return ResourceManager.GetString("GuideTitleFormat", resourceCulture);
            }
        }

        internal static string GuideCapacityFormat {
            get {
                return ResourceManager.GetString("GuideCapacityFormat", resourceCulture);
            }
        }

        internal static string GuideOpen {
            get {
                return ResourceManager.GetString("GuideOpen", resourceCulture);
            }
        }

        internal static string GuestAdults {
            get {
                return ResourceManager.GetString("GuestAdults", resourceCulture);
            }
        }

        internal static string GuestChildren {
            get {
                return ResourceManager.GetString("GuestChildren", resourceCulture);
            }
        }

        internal static string GuestChildrenHint {
            get {
                return ResourceManager.GetString("GuestChildrenHint", resourceCulture);
            }
        }

        internal static string GuestChangeTitle {
            get {
                return ResourceManager.GetString("GuestChangeTitle", resourceCulture);
            }
        }

        internal static string GuestChange {
            get {
                return ResourceManager.GetString("GuestChange", resourceCulture);
            }
        }

        internal static string VisitGuests {
            get {
                return ResourceManager.GetString("VisitGuests", resourceCulture);
            }
        }

        internal static string GuestDetailFormat {
            get {
                return ResourceManager.GetString("GuestDetailFormat", resourceCulture);
            }
        }

        internal static string GuestAdultsFormat {
            get {
                return ResourceManager.GetString("GuestAdultsFormat", resourceCulture);
            }
        }

        internal static string VisitOpened {
            get {
                return ResourceManager.GetString("VisitOpened", resourceCulture);
            }
        }

        internal static string VisitOpenedFormat {
            get {
                return ResourceManager.GetString("VisitOpenedFormat", resourceCulture);
            }
        }

        internal static string VisitTotal {
            get {
                return ResourceManager.GetString("VisitTotal", resourceCulture);
            }
        }

        internal static string VisitOrders {
            get {
                return ResourceManager.GetString("VisitOrders", resourceCulture);
            }
        }

        internal static string VisitNoOrders {
            get {
                return ResourceManager.GetString("VisitNoOrders", resourceCulture);
            }
        }

        internal static string OrderTitleFormat {
            get {
                return ResourceManager.GetString("OrderTitleFormat", resourceCulture);
            }
        }

        internal static string VisitMove {
            get {
                return ResourceManager.GetString("VisitMove", resourceCulture);
            }
        }

        internal static string VisitClose {
            get {
                return ResourceManager.GetString("VisitClose", resourceCulture);
            }
        }

        internal static string VisitCancel {
            get {
                return ResourceManager.GetString("VisitCancel", resourceCulture);
            }
        }

        internal static string MoveTitle {
            get {
                return ResourceManager.GetString("MoveTitle", resourceCulture);
            }
        }

        internal static string MoveEmpty {
            get {
                return ResourceManager.GetString("MoveEmpty", resourceCulture);
            }
        }

        internal static string CloseTitle {
            get {
                return ResourceManager.GetString("CloseTitle", resourceCulture);
            }
        }

        internal static string CloseMessageFormat {
            get {
                return ResourceManager.GetString("CloseMessageFormat", resourceCulture);
            }
        }

        internal static string CloseHeldMessageFormat {
            get {
                return ResourceManager.GetString("CloseHeldMessageFormat", resourceCulture);
            }
        }

        internal static string CloseOk {
            get {
                return ResourceManager.GetString("CloseOk", resourceCulture);
            }
        }

        internal static string CancelTitle {
            get {
                return ResourceManager.GetString("CancelTitle", resourceCulture);
            }
        }

        internal static string CancelMessageFormat {
            get {
                return ResourceManager.GetString("CancelMessageFormat", resourceCulture);
            }
        }

        internal static string CancelOk {
            get {
                return ResourceManager.GetString("CancelOk", resourceCulture);
            }
        }

        internal static string VisitAddOrder {
            get {
                return ResourceManager.GetString("VisitAddOrder", resourceCulture);
            }
        }

        internal static string VisitReleaseFormat {
            get {
                return ResourceManager.GetString("VisitReleaseFormat", resourceCulture);
            }
        }

        internal static string ReleaseTitle {
            get {
                return ResourceManager.GetString("ReleaseTitle", resourceCulture);
            }
        }

        internal static string ReleaseMessageFormat {
            get {
                return ResourceManager.GetString("ReleaseMessageFormat", resourceCulture);
            }
        }

        internal static string ReleaseOk {
            get {
                return ResourceManager.GetString("ReleaseOk", resourceCulture);
            }
        }

        internal static string VisitBill {
            get {
                return ResourceManager.GetString("VisitBill", resourceCulture);
            }
        }

        internal static string LineCancelTitle {
            get {
                return ResourceManager.GetString("LineCancelTitle", resourceCulture);
            }
        }

        internal static string LineCancelQuantity {
            get {
                return ResourceManager.GetString("LineCancelQuantity", resourceCulture);
            }
        }

        internal static string LineCancelOk {
            get {
                return ResourceManager.GetString("LineCancelOk", resourceCulture);
            }
        }

        internal static string BillTitleFormat {
            get {
                return ResourceManager.GetString("BillTitleFormat", resourceCulture);
            }
        }

        internal static string BillEmpty {
            get {
                return ResourceManager.GetString("BillEmpty", resourceCulture);
            }
        }

        internal static string BillTotal {
            get {
                return ResourceManager.GetString("BillTotal", resourceCulture);
            }
        }

        internal static string BillTaxFormat {
            get {
                return ResourceManager.GetString("BillTaxFormat", resourceCulture);
            }
        }

        internal static string BillPaid {
            get {
                return ResourceManager.GetString("BillPaid", resourceCulture);
            }
        }

        internal static string BillBalance {
            get {
                return ResourceManager.GetString("BillBalance", resourceCulture);
            }
        }

        internal static string BillUnserved {
            get {
                return ResourceManager.GetString("BillUnserved", resourceCulture);
            }
        }

        internal static string BillStart {
            get {
                return ResourceManager.GetString("BillStart", resourceCulture);
            }
        }

        internal static string BillCancel {
            get {
                return ResourceManager.GetString("BillCancel", resourceCulture);
            }
        }

        internal static string ProxyOrderTitleFormat {
            get {
                return ResourceManager.GetString("ProxyOrderTitleFormat", resourceCulture);
            }
        }

        internal static string OrderCartFormat {
            get {
                return ResourceManager.GetString("OrderCartFormat", resourceCulture);
            }
        }

        internal static string OrderCartEmpty {
            get {
                return ResourceManager.GetString("OrderCartEmpty", resourceCulture);
            }
        }

        internal static string OrderSubmit {
            get {
                return ResourceManager.GetString("OrderSubmit", resourceCulture);
            }
        }

        internal static string OrderSubmitFormat {
            get {
                return ResourceManager.GetString("OrderSubmitFormat", resourceCulture);
            }
        }

        internal static string OrderSubmitMessageFormat {
            get {
                return ResourceManager.GetString("OrderSubmitMessageFormat", resourceCulture);
            }
        }

        internal static string OrderDiscardTitle {
            get {
                return ResourceManager.GetString("OrderDiscardTitle", resourceCulture);
            }
        }

        internal static string OrderDiscardMessage {
            get {
                return ResourceManager.GetString("OrderDiscardMessage", resourceCulture);
            }
        }

        internal static string OrderDiscardOk {
            get {
                return ResourceManager.GetString("OrderDiscardOk", resourceCulture);
            }
        }

        internal static string OrderRemoveTitle {
            get {
                return ResourceManager.GetString("OrderRemoveTitle", resourceCulture);
            }
        }

        internal static string OrderRemoveMessageFormat {
            get {
                return ResourceManager.GetString("OrderRemoveMessageFormat", resourceCulture);
            }
        }

        internal static string OrderRemoveOk {
            get {
                return ResourceManager.GetString("OrderRemoveOk", resourceCulture);
            }
        }

        internal static string OrderLimitTitle {
            get {
                return ResourceManager.GetString("OrderLimitTitle", resourceCulture);
            }
        }

        internal static string OrderLimitMessage {
            get {
                return ResourceManager.GetString("OrderLimitMessage", resourceCulture);
            }
        }

        internal static string OrderLinesLimitFormat {
            get {
                return ResourceManager.GetString("OrderLinesLimitFormat", resourceCulture);
            }
        }

        internal static string OrderConfirmRuleTitle {
            get {
                return ResourceManager.GetString("OrderConfirmRuleTitle", resourceCulture);
            }
        }

        internal static string OrderConfirmRuleOk {
            get {
                return ResourceManager.GetString("OrderConfirmRuleOk", resourceCulture);
            }
        }

        internal static string OrderConfirmRuleFallback {
            get {
                return ResourceManager.GetString("OrderConfirmRuleFallback", resourceCulture);
            }
        }

        internal static string ItemAdd {
            get {
                return ResourceManager.GetString("ItemAdd", resourceCulture);
            }
        }

        internal static string ItemChooseOne {
            get {
                return ResourceManager.GetString("ItemChooseOne", resourceCulture);
            }
        }

        internal static string ItemOptional {
            get {
                return ResourceManager.GetString("ItemOptional", resourceCulture);
            }
        }

        internal static string ItemChooseUpToFormat {
            get {
                return ResourceManager.GetString("ItemChooseUpToFormat", resourceCulture);
            }
        }

        internal static string ItemTiming {
            get {
                return ResourceManager.GetString("ItemTiming", resourceCulture);
            }
        }

        internal static string ItemTimingNow {
            get {
                return ResourceManager.GetString("ItemTimingNow", resourceCulture);
            }
        }

        internal static string ItemTimingAfterMeal {
            get {
                return ResourceManager.GetString("ItemTimingAfterMeal", resourceCulture);
            }
        }

        internal static string ItemQuantity {
            get {
                return ResourceManager.GetString("ItemQuantity", resourceCulture);
            }
        }

        internal static string StatusHeld {
            get {
                return ResourceManager.GetString("StatusHeld", resourceCulture);
            }
        }

        internal static string StatusOrdered {
            get {
                return ResourceManager.GetString("StatusOrdered", resourceCulture);
            }
        }

        internal static string StatusCooking {
            get {
                return ResourceManager.GetString("StatusCooking", resourceCulture);
            }
        }

        internal static string StatusReady {
            get {
                return ResourceManager.GetString("StatusReady", resourceCulture);
            }
        }

        internal static string StatusServed {
            get {
                return ResourceManager.GetString("StatusServed", resourceCulture);
            }
        }

        internal static string StatusCancelled {
            get {
                return ResourceManager.GetString("StatusCancelled", resourceCulture);
            }
        }

        internal static string CallAcknowledge {
            get {
                return ResourceManager.GetString("CallAcknowledge", resourceCulture);
            }
        }

        internal static string CallAcknowledged {
            get {
                return ResourceManager.GetString("CallAcknowledged", resourceCulture);
            }
        }

        internal static string CallComplete {
            get {
                return ResourceManager.GetString("CallComplete", resourceCulture);
            }
        }

        internal static string CallsEmpty {
            get {
                return ResourceManager.GetString("CallsEmpty", resourceCulture);
            }
        }

        internal static string ServeLine {
            get {
                return ResourceManager.GetString("ServeLine", resourceCulture);
            }
        }

        internal static string ServeAll {
            get {
                return ResourceManager.GetString("ServeAll", resourceCulture);
            }
        }

        internal static string ServingEmpty {
            get {
                return ResourceManager.GetString("ServingEmpty", resourceCulture);
            }
        }

        internal static string ServingPaid {
            get {
                return ResourceManager.GetString("ServingPaid", resourceCulture);
            }
        }

        internal static string StockTabLimited {
            get {
                return ResourceManager.GetString("StockTabLimited", resourceCulture);
            }
        }

        internal static string StockTabOptions {
            get {
                return ResourceManager.GetString("StockTabOptions", resourceCulture);
            }
        }

        internal static string StockAvailable {
            get {
                return ResourceManager.GetString("StockAvailable", resourceCulture);
            }
        }

        internal static string StockSetRemaining {
            get {
                return ResourceManager.GetString("StockSetRemaining", resourceCulture);
            }
        }

        internal static string StockSoldOut {
            get {
                return ResourceManager.GetString("StockSoldOut", resourceCulture);
            }
        }

        internal static string StockRemainingFormat {
            get {
                return ResourceManager.GetString("StockRemainingFormat", resourceCulture);
            }
        }

        internal static string StockCurrentFormat {
            get {
                return ResourceManager.GetString("StockCurrentFormat", resourceCulture);
            }
        }

        internal static string StockRemainingTitle {
            get {
                return ResourceManager.GetString("StockRemainingTitle", resourceCulture);
            }
        }

        internal static string StockEmptyLimited {
            get {
                return ResourceManager.GetString("StockEmptyLimited", resourceCulture);
            }
        }

        internal static string StockEmpty {
            get {
                return ResourceManager.GetString("StockEmpty", resourceCulture);
            }
        }

        internal static string StockReset {
            get {
                return ResourceManager.GetString("StockReset", resourceCulture);
            }
        }

        internal static string StockResetMessage {
            get {
                return ResourceManager.GetString("StockResetMessage", resourceCulture);
            }
        }

        internal static string StockResetOk {
            get {
                return ResourceManager.GetString("StockResetOk", resourceCulture);
            }
        }

        internal static string OrderingPause {
            get {
                return ResourceManager.GetString("OrderingPause", resourceCulture);
            }
        }

        internal static string OrderingResume {
            get {
                return ResourceManager.GetString("OrderingResume", resourceCulture);
            }
        }

        internal static string OrderingPauseMessage {
            get {
                return ResourceManager.GetString("OrderingPauseMessage", resourceCulture);
            }
        }

        internal static string OrderingPauseOk {
            get {
                return ResourceManager.GetString("OrderingPauseOk", resourceCulture);
            }
        }

        internal static string ErrorUnavailable {
            get {
                return ResourceManager.GetString("ErrorUnavailable", resourceCulture);
            }
        }

        internal static string ErrorUnauthorized {
            get {
                return ResourceManager.GetString("ErrorUnauthorized", resourceCulture);
            }
        }

        internal static string ErrorTenantSuspended {
            get {
                return ResourceManager.GetString("ErrorTenantSuspended", resourceCulture);
            }
        }

        internal static string ErrorPairingCodeInvalid {
            get {
                return ResourceManager.GetString("ErrorPairingCodeInvalid", resourceCulture);
            }
        }

        internal static string ErrorDeviceKind {
            get {
                return ResourceManager.GetString("ErrorDeviceKind", resourceCulture);
            }
        }

        internal static string ErrorTableOccupied {
            get {
                return ResourceManager.GetString("ErrorTableOccupied", resourceCulture);
            }
        }

        internal static string ErrorVersionMismatch {
            get {
                return ResourceManager.GetString("ErrorVersionMismatch", resourceCulture);
            }
        }

        internal static string ErrorVisitHasOrders {
            get {
                return ResourceManager.GetString("ErrorVisitHasOrders", resourceCulture);
            }
        }

        internal static string ErrorCheckoutInProgress {
            get {
                return ResourceManager.GetString("ErrorCheckoutInProgress", resourceCulture);
            }
        }

        internal static string ErrorVisitNotOpen {
            get {
                return ResourceManager.GetString("ErrorVisitNotOpen", resourceCulture);
            }
        }

        internal static string ErrorNotFound {
            get {
                return ResourceManager.GetString("ErrorNotFound", resourceCulture);
            }
        }

        internal static string ErrorLineStatusInvalid {
            get {
                return ResourceManager.GetString("ErrorLineStatusInvalid", resourceCulture);
            }
        }

        internal static string ErrorOrderingPaused {
            get {
                return ResourceManager.GetString("ErrorOrderingPaused", resourceCulture);
            }
        }

        internal static string ErrorLastOrderPassed {
            get {
                return ResourceManager.GetString("ErrorLastOrderPassed", resourceCulture);
            }
        }

        internal static string ErrorMenuChanged {
            get {
                return ResourceManager.GetString("ErrorMenuChanged", resourceCulture);
            }
        }

        internal static string ErrorItemSoldOut {
            get {
                return ResourceManager.GetString("ErrorItemSoldOut", resourceCulture);
            }
        }

        internal static string ErrorStockInsufficient {
            get {
                return ResourceManager.GetString("ErrorStockInsufficient", resourceCulture);
            }
        }

        internal static string ErrorLimitExceeded {
            get {
                return ResourceManager.GetString("ErrorLimitExceeded", resourceCulture);
            }
        }

        internal static string ErrorConfirmationRequired {
            get {
                return ResourceManager.GetString("ErrorConfirmationRequired", resourceCulture);
            }
        }

        internal static string ErrorQuantityExceeded {
            get {
                return ResourceManager.GetString("ErrorQuantityExceeded", resourceCulture);
            }
        }

        internal static string ErrorOptionInvalid {
            get {
                return ResourceManager.GetString("ErrorOptionInvalid", resourceCulture);
            }
        }

        internal static string ErrorDuplicateIdMismatch {
            get {
                return ResourceManager.GetString("ErrorDuplicateIdMismatch", resourceCulture);
            }
        }

        internal static string ErrorBillChanged {
            get {
                return ResourceManager.GetString("ErrorBillChanged", resourceCulture);
            }
        }

        internal static string ErrorGeneric {
            get {
                return ResourceManager.GetString("ErrorGeneric", resourceCulture);
            }
        }

        internal static string CallWatchChannel {
            get {
                return ResourceManager.GetString("CallWatchChannel", resourceCulture);
            }
        }

        internal static string CallWatchTitle {
            get {
                return ResourceManager.GetString("CallWatchTitle", resourceCulture);
            }
        }

        internal static string CallWatchText {
            get {
                return ResourceManager.GetString("CallWatchText", resourceCulture);
            }
        }

        internal static string BillCancelUnavailable {
            get {
                return ResourceManager.GetString("BillCancelUnavailable", resourceCulture);
            }
        }

        internal static string ErrorLineCancelInvalid {
            get {
                return ResourceManager.GetString("ErrorLineCancelInvalid", resourceCulture);
            }
        }
    }
}
